name = "wordgames"
main = "src/index.js"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "wordgames.nibblesnbits.net", custom_domain = true }
]

[assets]
directory = "public"
binding = "ASSETS"

[durable_objects]
bindings = [
  { name = "GAME_SESSION", class_name = "GameSession" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameSession"]
